create table if not exists public.offerpsp_experience_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in (
    'hero_cta_click',
    'process_click',
    'vertical_brief_click',
    'lead_form_open',
    'lead_form_start',
    'lead_consent_checked',
    'lead_submit_attempt',
    'lead_submit_success',
    'lead_submit_failure'
  )),
  flow_id uuid not null,
  page_path text not null check (length(page_path) between 1 and 160),
  placement text check (placement is null or length(placement) between 1 and 80),
  is_qa boolean not null default false,
  occurred_at timestamptz not null default now()
);

alter table public.offerpsp_experience_events enable row level security;

revoke all on table public.offerpsp_experience_events from public, anon, authenticated;
grant insert, select, delete on table public.offerpsp_experience_events to service_role;
grant usage, select on sequence public.offerpsp_experience_events_id_seq to service_role;
grant select on table public.offerpsp_experience_events to authenticated;

drop policy if exists offerpsp_experience_events_staff_read on public.offerpsp_experience_events;
create policy offerpsp_experience_events_staff_read
  on public.offerpsp_experience_events
  for select
  to authenticated
  using ((select public.is_offerpsp_staff()));

create index if not exists offerpsp_experience_events_live_funnel_idx
  on public.offerpsp_experience_events (event_name, occurred_at desc)
  where is_qa = false;

create index if not exists offerpsp_experience_events_flow_idx
  on public.offerpsp_experience_events (flow_id, occurred_at);

create extension if not exists pgcrypto with schema extensions;

grant insert on table public.offerpsp_experience_events to anon;
grant usage on sequence public.offerpsp_experience_events_id_seq to anon;

drop policy if exists offerpsp_experience_events_server_ingest on public.offerpsp_experience_events;
create policy offerpsp_experience_events_server_ingest
  on public.offerpsp_experience_events
  for insert
  to anon
  with check (
    pg_catalog.encode(
      extensions.digest(
        pg_catalog.convert_to(
          coalesce(
            nullif(pg_catalog.current_setting('request.headers', true), '')::jsonb
              ->> 'x-offerpsp-ingest-secret',
            ''
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    ) = '659e0a9603f4e6b0bff512cb7cce80432d6bafa6288850a233fc8f84b93d2636'
  );

comment on table public.offerpsp_experience_events is
  'Privacy-safe public acquisition funnel. Stores only approved event names, a random flow ID, public page path, safe placement and QA marker; never form values.';
